// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export class AndroidAppCredentials extends pulumi.CustomResource {
    /**
     * Get an existing AndroidAppCredentials resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: AndroidAppCredentialsState, opts?: pulumi.CustomResourceOptions): AndroidAppCredentials {
        return new AndroidAppCredentials(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'eas:index/androidAppCredentials:AndroidAppCredentials';

    /**
     * Returns true if the given object is an instance of AndroidAppCredentials.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is AndroidAppCredentials {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === AndroidAppCredentials.__pulumiType;
    }

    /**
     * EAS App Id
     */
    public readonly appId!: pulumi.Output<string>;
    /**
     * EAS Android Build Credentials
     */
    public readonly buildCredentials!: pulumi.Output<outputs.AndroidAppCredentialsBuildCredential[] | undefined>;
    /**
     * FCM Google Service Account Key Id
     */
    public readonly fcmKey!: pulumi.Output<string | undefined>;
    /**
     * Google Service Account Key Id
     */
    public readonly googleServiceAccountKeyId!: pulumi.Output<string>;
    /**
     * Identifier of the Android App
     */
    public readonly identifier!: pulumi.Output<string>;

    /**
     * Create a AndroidAppCredentials resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: AndroidAppCredentialsArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: AndroidAppCredentialsArgs | AndroidAppCredentialsState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as AndroidAppCredentialsState | undefined;
            resourceInputs["appId"] = state ? state.appId : undefined;
            resourceInputs["buildCredentials"] = state ? state.buildCredentials : undefined;
            resourceInputs["fcmKey"] = state ? state.fcmKey : undefined;
            resourceInputs["googleServiceAccountKeyId"] = state ? state.googleServiceAccountKeyId : undefined;
            resourceInputs["identifier"] = state ? state.identifier : undefined;
        } else {
            const args = argsOrState as AndroidAppCredentialsArgs | undefined;
            if ((!args || args.appId === undefined) && !opts.urn) {
                throw new Error("Missing required property 'appId'");
            }
            if ((!args || args.googleServiceAccountKeyId === undefined) && !opts.urn) {
                throw new Error("Missing required property 'googleServiceAccountKeyId'");
            }
            if ((!args || args.identifier === undefined) && !opts.urn) {
                throw new Error("Missing required property 'identifier'");
            }
            resourceInputs["appId"] = args ? args.appId : undefined;
            resourceInputs["buildCredentials"] = args ? args.buildCredentials : undefined;
            resourceInputs["fcmKey"] = args?.fcmKey ? pulumi.secret(args.fcmKey) : undefined;
            resourceInputs["googleServiceAccountKeyId"] = args ? args.googleServiceAccountKeyId : undefined;
            resourceInputs["identifier"] = args ? args.identifier : undefined;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const secretOpts = { additionalSecretOutputs: ["fcmKey"] };
        opts = pulumi.mergeOptions(opts, secretOpts);
        super(AndroidAppCredentials.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering AndroidAppCredentials resources.
 */
export interface AndroidAppCredentialsState {
    /**
     * EAS App Id
     */
    appId?: pulumi.Input<string>;
    /**
     * EAS Android Build Credentials
     */
    buildCredentials?: pulumi.Input<pulumi.Input<inputs.AndroidAppCredentialsBuildCredential>[]>;
    /**
     * FCM Google Service Account Key Id
     */
    fcmKey?: pulumi.Input<string>;
    /**
     * Google Service Account Key Id
     */
    googleServiceAccountKeyId?: pulumi.Input<string>;
    /**
     * Identifier of the Android App
     */
    identifier?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a AndroidAppCredentials resource.
 */
export interface AndroidAppCredentialsArgs {
    /**
     * EAS App Id
     */
    appId: pulumi.Input<string>;
    /**
     * EAS Android Build Credentials
     */
    buildCredentials?: pulumi.Input<pulumi.Input<inputs.AndroidAppCredentialsBuildCredential>[]>;
    /**
     * FCM Google Service Account Key Id
     */
    fcmKey?: pulumi.Input<string>;
    /**
     * Google Service Account Key Id
     */
    googleServiceAccountKeyId: pulumi.Input<string>;
    /**
     * Identifier of the Android App
     */
    identifier: pulumi.Input<string>;
}
