// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class AppVariable extends pulumi.CustomResource {
    /**
     * Get an existing AppVariable resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: AppVariableState, opts?: pulumi.CustomResourceOptions): AppVariable {
        return new AppVariable(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'eas:index/appVariable:AppVariable';

    /**
     * Returns true if the given object is an instance of AppVariable.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is AppVariable {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === AppVariable.__pulumiType;
    }

    /**
     * The id of the app for the environment variable
     */
    public readonly appId!: pulumi.Output<string>;
    /**
     * The environments of the app for the environment variable
     */
    public readonly environments!: pulumi.Output<string[]>;
    /**
     * The name of the app for the environment variable
     */
    public readonly name!: pulumi.Output<string>;
    /**
     * The value of the app for the environment variable
     */
    public readonly value!: pulumi.Output<string>;
    /**
     * The visibility of the app for the environment variable
     */
    public readonly visibility!: pulumi.Output<string>;

    /**
     * Create a AppVariable resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: AppVariableArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: AppVariableArgs | AppVariableState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as AppVariableState | undefined;
            resourceInputs["appId"] = state ? state.appId : undefined;
            resourceInputs["environments"] = state ? state.environments : undefined;
            resourceInputs["name"] = state ? state.name : undefined;
            resourceInputs["value"] = state ? state.value : undefined;
            resourceInputs["visibility"] = state ? state.visibility : undefined;
        } else {
            const args = argsOrState as AppVariableArgs | undefined;
            if ((!args || args.appId === undefined) && !opts.urn) {
                throw new Error("Missing required property 'appId'");
            }
            if ((!args || args.environments === undefined) && !opts.urn) {
                throw new Error("Missing required property 'environments'");
            }
            if ((!args || args.value === undefined) && !opts.urn) {
                throw new Error("Missing required property 'value'");
            }
            if ((!args || args.visibility === undefined) && !opts.urn) {
                throw new Error("Missing required property 'visibility'");
            }
            resourceInputs["appId"] = args ? args.appId : undefined;
            resourceInputs["environments"] = args ? args.environments : undefined;
            resourceInputs["name"] = args ? args.name : undefined;
            resourceInputs["value"] = args ? args.value : undefined;
            resourceInputs["visibility"] = args ? args.visibility : undefined;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(AppVariable.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering AppVariable resources.
 */
export interface AppVariableState {
    /**
     * The id of the app for the environment variable
     */
    appId?: pulumi.Input<string>;
    /**
     * The environments of the app for the environment variable
     */
    environments?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * The name of the app for the environment variable
     */
    name?: pulumi.Input<string>;
    /**
     * The value of the app for the environment variable
     */
    value?: pulumi.Input<string>;
    /**
     * The visibility of the app for the environment variable
     */
    visibility?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a AppVariable resource.
 */
export interface AppVariableArgs {
    /**
     * The id of the app for the environment variable
     */
    appId: pulumi.Input<string>;
    /**
     * The environments of the app for the environment variable
     */
    environments: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * The name of the app for the environment variable
     */
    name?: pulumi.Input<string>;
    /**
     * The value of the app for the environment variable
     */
    value: pulumi.Input<string>;
    /**
     * The visibility of the app for the environment variable
     */
    visibility: pulumi.Input<string>;
}
