// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getAppStoreApiKey(args: GetAppStoreApiKeyArgs, opts?: pulumi.InvokeOptions): Promise<GetAppStoreApiKeyResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("eas:index/getAppStoreApiKey:getAppStoreApiKey", {
        "identifier": args.identifier,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getAppStoreApiKey.
 */
export interface GetAppStoreApiKeyArgs {
    identifier: string;
}

/**
 * A collection of values returned by getAppStoreApiKey.
 */
export interface GetAppStoreApiKeyResult {
    readonly id: string;
    readonly identifier: string;
    readonly issuerIdentifier: string;
    readonly name: string;
}
export function getAppStoreApiKeyOutput(args: GetAppStoreApiKeyOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetAppStoreApiKeyResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("eas:index/getAppStoreApiKey:getAppStoreApiKey", {
        "identifier": args.identifier,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getAppStoreApiKey.
 */
export interface GetAppStoreApiKeyOutputArgs {
    identifier: pulumi.Input<string>;
}
