// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getGoogleServiceAccountKey(args: GetGoogleServiceAccountKeyArgs, opts?: pulumi.InvokeOptions): Promise<GetGoogleServiceAccountKeyResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("eas:index/getGoogleServiceAccountKey:getGoogleServiceAccountKey", {
        "projectIdentifier": args.projectIdentifier,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getGoogleServiceAccountKey.
 */
export interface GetGoogleServiceAccountKeyArgs {
    projectIdentifier: string;
}

/**
 * A collection of values returned by getGoogleServiceAccountKey.
 */
export interface GetGoogleServiceAccountKeyResult {
    readonly clientEmail: string;
    readonly clientIdentifier: string;
    readonly id: string;
    readonly projectIdentifier: string;
}
export function getGoogleServiceAccountKeyOutput(args: GetGoogleServiceAccountKeyOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetGoogleServiceAccountKeyResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("eas:index/getGoogleServiceAccountKey:getGoogleServiceAccountKey", {
        "projectIdentifier": args.projectIdentifier,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getGoogleServiceAccountKey.
 */
export interface GetGoogleServiceAccountKeyOutputArgs {
    projectIdentifier: pulumi.Input<string>;
}
