// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getIosCertificate(args: GetIosCertificateArgs, opts?: pulumi.InvokeOptions): Promise<GetIosCertificateResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("eas:index/getIosCertificate:getIosCertificate", {
        "serialNumber": args.serialNumber,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getIosCertificate.
 */
export interface GetIosCertificateArgs {
    serialNumber: string;
}

/**
 * A collection of values returned by getIosCertificate.
 */
export interface GetIosCertificateResult {
    readonly id: string;
    readonly serialNumber: string;
}
export function getIosCertificateOutput(args: GetIosCertificateOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetIosCertificateResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("eas:index/getIosCertificate:getIosCertificate", {
        "serialNumber": args.serialNumber,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getIosCertificate.
 */
export interface GetIosCertificateOutputArgs {
    serialNumber: pulumi.Input<string>;
}
