// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getIosPushKey(args: GetIosPushKeyArgs, opts?: pulumi.InvokeOptions): Promise<GetIosPushKeyResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("eas:index/getIosPushKey:getIosPushKey", {
        "identifier": args.identifier,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getIosPushKey.
 */
export interface GetIosPushKeyArgs {
    identifier: string;
}

/**
 * A collection of values returned by getIosPushKey.
 */
export interface GetIosPushKeyResult {
    readonly id: string;
    readonly identifier: string;
}
export function getIosPushKeyOutput(args: GetIosPushKeyOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetIosPushKeyResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("eas:index/getIosPushKey:getIosPushKey", {
        "identifier": args.identifier,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getIosPushKey.
 */
export interface GetIosPushKeyOutputArgs {
    identifier: pulumi.Input<string>;
}
