// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export class IosAppCredentials extends pulumi.CustomResource {
    /**
     * Get an existing IosAppCredentials resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: IosAppCredentialsState, opts?: pulumi.CustomResourceOptions): IosAppCredentials {
        return new IosAppCredentials(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'eas:index/iosAppCredentials:IosAppCredentials';

    /**
     * Returns true if the given object is an instance of IosAppCredentials.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is IosAppCredentials {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === IosAppCredentials.__pulumiType;
    }

    /**
     * EAS App Id
     */
    public readonly appId!: pulumi.Output<string>;
    /**
     * EAS App Identifier Id
     */
    public readonly appIdentifierId!: pulumi.Output<string>;
    /**
     * EAS App Build Credentials for App Store
     */
    public readonly appStore!: pulumi.Output<outputs.IosAppCredentialsAppStore | undefined>;
    /**
     * EAS App Store Api Key Id
     */
    public readonly appStoreApiKeyId!: pulumi.Output<string | undefined>;
    /**
     * EAS Apple Push Key Id
     */
    public readonly pushKeyId!: pulumi.Output<string | undefined>;

    /**
     * Create a IosAppCredentials resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: IosAppCredentialsArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: IosAppCredentialsArgs | IosAppCredentialsState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as IosAppCredentialsState | undefined;
            resourceInputs["appId"] = state ? state.appId : undefined;
            resourceInputs["appIdentifierId"] = state ? state.appIdentifierId : undefined;
            resourceInputs["appStore"] = state ? state.appStore : undefined;
            resourceInputs["appStoreApiKeyId"] = state ? state.appStoreApiKeyId : undefined;
            resourceInputs["pushKeyId"] = state ? state.pushKeyId : undefined;
        } else {
            const args = argsOrState as IosAppCredentialsArgs | undefined;
            if ((!args || args.appId === undefined) && !opts.urn) {
                throw new Error("Missing required property 'appId'");
            }
            if ((!args || args.appIdentifierId === undefined) && !opts.urn) {
                throw new Error("Missing required property 'appIdentifierId'");
            }
            resourceInputs["appId"] = args ? args.appId : undefined;
            resourceInputs["appIdentifierId"] = args ? args.appIdentifierId : undefined;
            resourceInputs["appStore"] = args ? args.appStore : undefined;
            resourceInputs["appStoreApiKeyId"] = args ? args.appStoreApiKeyId : undefined;
            resourceInputs["pushKeyId"] = args ? args.pushKeyId : undefined;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(IosAppCredentials.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering IosAppCredentials resources.
 */
export interface IosAppCredentialsState {
    /**
     * EAS App Id
     */
    appId?: pulumi.Input<string>;
    /**
     * EAS App Identifier Id
     */
    appIdentifierId?: pulumi.Input<string>;
    /**
     * EAS App Build Credentials for App Store
     */
    appStore?: pulumi.Input<inputs.IosAppCredentialsAppStore>;
    /**
     * EAS App Store Api Key Id
     */
    appStoreApiKeyId?: pulumi.Input<string>;
    /**
     * EAS Apple Push Key Id
     */
    pushKeyId?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a IosAppCredentials resource.
 */
export interface IosAppCredentialsArgs {
    /**
     * EAS App Id
     */
    appId: pulumi.Input<string>;
    /**
     * EAS App Identifier Id
     */
    appIdentifierId: pulumi.Input<string>;
    /**
     * EAS App Build Credentials for App Store
     */
    appStore?: pulumi.Input<inputs.IosAppCredentialsAppStore>;
    /**
     * EAS App Store Api Key Id
     */
    appStoreApiKeyId?: pulumi.Input<string>;
    /**
     * EAS Apple Push Key Id
     */
    pushKeyId?: pulumi.Input<string>;
}
