// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

declare var exports: any;
const __config = new pulumi.Config("eas");

/**
 * Expo user/organization account name. You can set this via `EXPO_ACCOUNT_NAME` environment variable.
 */
export declare const accountName: string | undefined;
Object.defineProperty(exports, "accountName", {
    get() {
        return __config.get("accountName");
    },
    enumerable: true,
});

/**
 * Expo personal access token or robot access token. You can set this via `EXPO TOKEN` environment variable.
 */
export declare const token: string | undefined;
Object.defineProperty(exports, "token", {
    get() {
        return __config.get("token");
    },
    enumerable: true,
});

